@echo off
REM Sentinel-IDE build — configures + builds with the VS-bundled CMake/Ninja + MSVC.
REM Run from anywhere: scripts\build.bat   (output: build\Sentinel-IDE.exe)
setlocal
set "VS=C:\Program Files\Microsoft Visual Studio\18\Community"
call "%VS%\VC\Auxiliary\Build\vcvars64.bat" >nul
set "CMAKE=%VS%\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
set "NINJA=%VS%\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"

REM --- Version stamping -------------------------------------------------------
REM Marketing version is fixed; the build number auto-increments on every build.
REM Counter persists in packaging\build_number.txt; the composed macros are written
REM to build\generated\Version.h, consumed by both the C++ sources and the .rc.
set "MKT=0.1.0"
set "MKTRC=0,1,0"
set "NUMFILE=%~dp0..\packaging\build_number.txt"
set "BUILDNO="
if exist "%NUMFILE%" set /p BUILDNO=<"%NUMFILE%"
if not defined BUILDNO set "BUILDNO=0"
set /a BUILDNO=BUILDNO+1 || exit /b 1
>"%NUMFILE%" echo %BUILDNO%
set "GENDIR=%~dp0..\build\generated"
if not exist "%GENDIR%" mkdir "%GENDIR%"
set "VERH=%GENDIR%\Version.h"
>"%VERH%"  echo #pragma once
>>"%VERH%" echo // Generated by scripts\build.bat - do not edit by hand.
>>"%VERH%" echo #define SENTINEL_BUILD_NUMBER %BUILDNO%
>>"%VERH%" echo #define SENTINEL_VERSION_MARKETING "%MKT%"
>>"%VERH%" echo #define SENTINEL_VERSION_DISPLAY "%MKT% (build %BUILDNO%)"
>>"%VERH%" echo #define SENTINEL_VERSION_DISPLAY_W L"%MKT% (build %BUILDNO%)"
>>"%VERH%" echo #define SENTINEL_FILEVERSION %MKTRC%,%BUILDNO%
>>"%VERH%" echo #define SENTINEL_FILEVERSION_STR "%MKT%.%BUILDNO%"
echo BUILD_NUMBER %BUILDNO%

REM --- Lines-of-code accounting (About box) -----------------------------------
REM Counts the IDE's source by language and writes build\generated\Loc.h. The
REM grand total is computed *in Sentinel* (tools\loc.sentinel via snc) when the
REM compiler is present; otherwise loc.ps1 falls back to its own count. vcvars is
REM already in this env, so snc's link step works. Non-fatal: never blocks a build.
set "SNC=G:\Sentinel-lang\target\debug\snc.exe"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0loc.ps1" -Root "%~dp0.." -Gen "%GENDIR%" -Snc "%SNC%"

"%CMAKE%" -S "%~dp0.." -B "%~dp0..\build" -G Ninja -DCMAKE_MAKE_PROGRAM="%NINJA%" -DCMAKE_BUILD_TYPE=Debug || exit /b 1
"%CMAKE%" --build "%~dp0..\build" || exit /b 1
echo BUILD_OK
