@echo off
REM Sentinel-IDE build — configures + builds with the VS-bundled CMake/Ninja + MSVC.
REM Run from anywhere: scripts\build.bat   (output: build\Sentinel-IDE.exe)
setlocal
set "VS=C:\Program Files\Microsoft Visual Studio\18\Community"
call "%VS%\VC\Auxiliary\Build\vcvars64.bat" >nul
set "CMAKE=%VS%\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
set "NINJA=%VS%\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"

REM --- Version stamping -------------------------------------------------------
REM Marketing version is fixed; the build number is DERIVED FROM GIT — the commit
REM count on HEAD — so the same commit always stamps the same version and a released
REM artifact can be rebuilt from its tag. It replaces a packaging\build_number.txt
REM counter that incremented on every run (including failed ones), was tied to nothing
REM reproducible, and dirtied a tracked file on every build. That mattered once the
REM number started naming shipped installers and driving WinSparkle's version compare.
REM
REM BUILDBASE keeps the sequence above the retired counter's high-water mark (38), so
REM the version never goes backwards across the switch. Nothing had been released when
REM this changed, so the offset is cosmetic continuity, not a correctness requirement —
REM but a version that regresses is exactly the bug WinSparkle cannot recover from.
set "MKT=0.1.4"
set "MKTRC=0,1,4"
set "BUILDBASE=100"
set "BUILDNO="
for /f %%i in ('git -C "%~dp0.." rev-list --count HEAD 2^>nul') do set "BUILDNO=%%i"
if not defined BUILDNO (
  echo ERROR: cannot derive the build number - 'git rev-list --count HEAD' failed.
  echo        Build from a git working tree ^(or fix git on PATH^).
  exit /b 1
)
set /a BUILDNO=BUILDNO+BUILDBASE || exit /b 1
REM A dirty tree means the binary does not correspond to the commit it is stamped with.
REM Fine while developing; never ship one — the version would name a commit whose
REM contents differ from what shipped.
set "DIRTY="
for /f %%i in ('git -C "%~dp0.." status --porcelain 2^>nul ^| find /c /v ""') do set "DIRTY=%%i"
if not "%DIRTY%"=="0" echo BUILD_DIRTY %DIRTY% uncommitted change^(s^) - build %BUILDNO% does not match commit contents
set "GENDIR=%~dp0..\build\generated"
if not exist "%GENDIR%" mkdir "%GENDIR%"
set "VERH=%GENDIR%\Version.h"
>"%VERH%"  echo #pragma once
>>"%VERH%" echo // Generated by scripts\build.bat - do not edit by hand.
>>"%VERH%" echo #define SENTINEL_BUILD_NUMBER %BUILDNO%
>>"%VERH%" echo #define SENTINEL_VERSION_MARKETING "%MKT%"
>>"%VERH%" echo #define SENTINEL_VERSION_DISPLAY "%MKT% (build %BUILDNO%)"
>>"%VERH%" echo #define SENTINEL_VERSION_DISPLAY_W L"%MKT% (build %BUILDNO%)"
>>"%VERH%" echo #define SENTINEL_FILEVERSION %MKTRC%,%BUILDNO%
>>"%VERH%" echo #define SENTINEL_FILEVERSION_STR "%MKT%.%BUILDNO%"
REM Wide form — WinSparkle's win_sparkle_set_app_details takes wchar_t*, and the
REM version it reports must be marketing.build so it compares against the appcast's
REM sparkle:version (the marketing version alone never advances).
>>"%VERH%" echo #define SENTINEL_FILEVERSION_STR_W L"%MKT%.%BUILDNO%"
echo BUILD_NUMBER %BUILDNO%

REM --- Lines-of-code accounting (About box) -----------------------------------
REM Counts the IDE's source by language and writes build\generated\Loc.h. The
REM grand total is computed *in Sentinel* (tools\loc.sentinel via snc) when the
REM compiler is present; otherwise loc.ps1 falls back to its own count. vcvars is
REM already in this env, so snc's link step works. Non-fatal: never blocks a build.
set "SNC=G:\Sentinel-lang\target\debug\snc.exe"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0loc.ps1" -Root "%~dp0.." -Gen "%GENDIR%" -Snc "%SNC%"

REM --- Sentinel-native parsers (PRODUCT logic in Sentinel) ---------------------
REM Compile src\sentinel\parsers.sentinel to ONE C-ABI static lib the host links, so
REM the shipped binary interprets snc's diagnostic + trust-manifest bytes in Sentinel
REM (ADR 0059). One lib on purpose: each Sentinel lib bundles the whole runtime, so two
REM would collide on sentinel_free_bytes / the allocator. vcvars is already in this env,
REM so snc's internal lib.exe step resolves. If snc is absent or the build fails, the lib
REM is simply not produced and CMake falls back to the C++ implementations (kept in
REM lockstep by tests\diag_xcheck.cpp + trust_xcheck.cpp). Never blocks a build.
set "SNCREL=G:\Sentinel-lang\target\release\snc.exe"
set "SNCLIBPATH=G:\Sentinel-lang\sentinel_library"
set "SNTLIB=%GENDIR%\parsers.lib"
if exist "%SNTLIB%" del /f /q "%SNTLIB%"
if exist "%SNCREL%" (
  "%SNCREL%" build --lib "%~dp0..\src\sentinel\parsers.sentinel" -o "%SNTLIB%" --emit-header "%GENDIR%\sentinel_parsers.h" --lib-path "%SNCLIBPATH%"
  if exist "%SNTLIB%" (echo SENTINEL_PARSERS_OK) else (echo SENTINEL_PARSERS_FALLBACK - snc lib build failed, using C++ parsers)
) else (
  echo SENTINEL_PARSERS_FALLBACK - snc not found, using C++ parsers
)

REM Release + STATIC CRT. Both halves matter, and the old Debug default was a shipping bug:
REM a /MDd binary imports MSVCP140D.dll / VCRUNTIME140D.dll / ucrtbased.dll, which ship only
REM with Visual Studio and are NOT licensed for redistribution — so every installer through
REM v0.1.3 failed to launch on any machine without VS ("VCRUNTIME140D.dll was not found").
REM MultiThreaded (/MT) links the CRT in, so the per-user installer needs no redistributable
REM and no admin rights. Verified: parsers.lib links under /MT, and the exe went 2.65 -> 0.78 MB.
"%CMAKE%" -S "%~dp0.." -B "%~dp0..\build" -G Ninja -DCMAKE_MAKE_PROGRAM="%NINJA%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded || exit /b 1
"%CMAKE%" --build "%~dp0..\build" || exit /b 1
echo BUILD_OK
