# Lines-of-code accounting for SentinelIDE's About box.
#
# Counts the IDE's own source by language (C++, Sentinel, Build), writes the
# numbers to <Gen>\Loc.h (consumed by AboutDialog.cpp), and — as dogfooding —
# hands the concatenated corpus to tools\loc.sentinel (compiled + run via snc)
# so the grand total is computed *by a Sentinel program*. Falls back to the
# PowerShell total if snc is unavailable, so the IDE build never depends on it.
#
#   powershell -File scripts\loc.ps1 -Root <repoRoot> -Gen <genDir> -Snc <snc.exe>
param([string]$Root, [string]$Gen, [string]$Snc = "")

$ErrorActionPreference = "Continue"
if (-not (Test-Path $Gen)) { New-Item -ItemType Directory -Force $Gen | Out-Null }

function Read-Text([string]$p) { try { return [System.IO.File]::ReadAllText($p) } catch { return "" } }
function Line-Count([string]$t) {
    if ($t.Length -eq 0) { return 0 }
    $n = ([regex]::Matches($t, "`n")).Count
    if ($t[$t.Length - 1] -ne "`n") { $n++ }   # a final line with no trailing newline still counts
    return $n
}

# --- enumerate the IDE's own source (not BMad skills, not reference repos) ---
$cpp = @(Get-ChildItem -Path "$Root\src" -Recurse -Include *.cpp,*.h -File -EA SilentlyContinue)
$snt = @(Get-ChildItem -Path "$Root\tools","$Root\examples" -Recurse -Include *.sentinel -File -EA SilentlyContinue)
$bld = @()
if (Test-Path "$Root\CMakeLists.txt") { $bld += Get-Item "$Root\CMakeLists.txt" }
$bld += @(Get-ChildItem -Path "$Root\scripts" -Recurse -Include *.bat,*.ps1 -File -EA SilentlyContinue)
$bld += @(Get-ChildItem -Path "$Root\packaging" -Recurse -Include *.rc,*.manifest -File -EA SilentlyContinue)

function Sum-Lines($files) {
    $s = 0
    foreach ($f in $files) { $s += Line-Count (Read-Text $f.FullName) }
    return $s
}
$locCpp = Sum-Lines $cpp
$locSnt = Sum-Lines $snt
$locBld = Sum-Lines $bld
$total  = $locCpp + $locSnt + $locBld

# --- build the corpus for the Sentinel counter (each file normalized to end in \n) ---
$sb = New-Object System.Text.StringBuilder
foreach ($f in @($cpp) + @($snt) + @($bld)) {
    $t = Read-Text $f.FullName
    [void]$sb.Append($t)
    if ($t.Length -eq 0 -or $t[$t.Length - 1] -ne "`n") { [void]$sb.Append("`n") }
}
[System.IO.File]::WriteAllText("$Gen\loc_corpus.txt", $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

# --- dogfood: let tools\loc.sentinel compute the grand total (snc + MSVC env) ---
$bySentinel = 0
$sentinelTotal = $total
if ($Snc -and (Test-Path $Snc) -and (Test-Path "$Root\tools\loc.sentinel")) {
    try {
        & $Snc build "$Root\tools\loc.sentinel" -o "$Gen\loc.exe" 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0 -and (Test-Path "$Gen\loc.exe")) {
            Push-Location $Gen
            try { & "$Gen\loc.exe" | Out-Null } finally { Pop-Location }
            if (Test-Path "$Gen\loc_total.txt") {
                $st = 0
                if ([int]::TryParse((Get-Content "$Gen\loc_total.txt" -Raw).Trim(), [ref]$st)) {
                    $sentinelTotal = $st; $bySentinel = 1
                }
            }
        }
    } catch { }
}

$h = @"
#pragma once
// Generated by scripts/loc.ps1 - do not edit. Lines of code by language.
// SENTINEL_LOC_TOTAL is computed by tools/loc.sentinel when SENTINEL_LOC_BY_SENTINEL=1.
#define SENTINEL_LOC_CPP $locCpp
#define SENTINEL_LOC_SENTINEL $locSnt
#define SENTINEL_LOC_BUILD $locBld
#define SENTINEL_LOC_TOTAL $sentinelTotal
#define SENTINEL_LOC_BY_SENTINEL $bySentinel
"@
[System.IO.File]::WriteAllText("$Gen\Loc.h", $h, (New-Object System.Text.UTF8Encoding($false)))
Write-Output "LOC cpp=$locCpp sentinel=$locSnt build=$locBld total=$sentinelTotal bySentinel=$bySentinel"
